app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'HomeController@index');

    Route::get('/home', 'HomeController@index');

    Route::get('/members/delete_selected', 'MembersController@delete_selected');

    Route::resource('members', 'MembersController');

    Route::resource('users', 'UsersController');

    Route::get('upload', function(){
        $user = App\User::first();
        return view('pages.users.upload',compact('user'));
    });

    Route::get('display','UsersController@showPhoto');

    Route::post('users/photos','UsersController@addPhoto');

    Route::get('/test', function(){
//        Auth::loginusingid(5);
//        Auth::logout();
        return view('test');
    });
});

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    protected $fillable = [
        'full_name',
        'dob',
        'gender',
        'perm_district',
        'perm_vdc',
        'perm_ward',
        'curr_vdc',
        'curr_district',
        'curr_ward',
        'citizenship_no',
        'contact_no',
        'email',
        'skype',
        'qualification',
        'specialization',
        'kind_of_help'
    ];
}

app/Http/Controllers/MembersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\MembersRequest;
use App\Member;
use App\Abode;
use Illuminate\Http\Request;

use App\Http\Requests;

class MembersController extends Controller
{
    /**
     * Function : __constructor
     * Function for Constructor
     */
    public function __construct()
    {
        /* This will call for authentication before allowing access
         * over other this module.
         */
//        $this->middleware('role:HR');
    }
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($search = $request->input('search')) {
            $members = Member::where('full_name', 'LIKE', '%'.$search.'%')
                ->orWhere('citizenship_no', 'LIKE', '%'.$search.'%')
                ->orWhere('contact_no', 'LIKE', '%'.$search.'%')
                ->orWhere('id', 'LIKE', '%'.$search.'%')->simplePaginate(50);
        }
        else {
            $members = Member::SimplePaginate(50);
        }

        return view('pages.members.index', compact('members','search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $submitText = ' Add ';
        $districts = Abode::distinct()->lists('district');
        $vdcs = Abode::lists('vdc');

        return view('pages.members.create',compact('districts','vdcs','submitText'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param MembersRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(MembersRequest $request)
    {
        Member::create($request->all());

        return redirect('members');
    }

    /**
     * Display the specified resource.
     *
     * @param Member $member
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function show(Member $member)
    {
        return view('pages.members.show',compact('member'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Member $member
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function edit(Member $member)
    {
        $submitText = ' Update ';
        $districts = Abode::distinct()->lists('district');
        $vdcs = Abode::lists('vdc');

        return view('pages.members.edit',compact('member','districts','vdcs','submitText'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param MembersRequest $request
     * @param Member $member
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(MembersRequest $request, Member $member)
    {
        $member->update($request->all());

        return redirect('members');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Member $member
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function destroy(Member $member)
    {
        $member->delete();

        return redirect('members');
    }
}

resources/views/pages/members/_createform.blade.php
<!-- Full Name Form Text Input -->
<div class="form-group{{ $errors->has('full_name') ? ' has-error' : '' }}">
    {!! Form::label('','Full Name ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-4">
        {!! Form::text('full_name',null,['class'=>'form-control']) !!}

        @if ($errors->has('full_name'))
            <span class="help-block">
                <strong>{{ $errors->first('full_name') }}</strong>
            </span>
        @endif
    </div>
</div>

<!-- Date of Birth Form Text Input -->
<!-- Date of Birth Form Text Input -->
<div class="form-group{{ $errors->has('dob') ? ' has-error' : '' }}">
    {!! Form::label('dob','Date of Birth ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-4">
        {!! Form::input('date','dob',null,['class'=>'form-control']) !!}

        @if ($errors->has('dob'))
            <span class="help-block">
                <strong>{{ $errors->first('dob') }}</strong>
            </span>
        @endif
    </div>
</div>


<!-- Citizenship No. Form Text Input -->
<div class="form-group{{ $errors->has('citizenship_no') ? ' has-error' : '' }}">
    {!! Form::label('citizenship_no','Citizenship No. ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-4">
        {!! Form::text('citizenship_no',null,['class'=>'form-control']) !!}

        @if ($errors->has('citizenship_no'))
            <span class="help-block">
                <strong>{{ $errors->first('citizenship_no') }}</strong>
            </span>
        @endif
    </div>
</div>

{{--Gender Form Radio Input --}}
<div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
    {!! Form::label('gender','Gender ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-4">
        <div class="radio">
            <label>
                <input name="gender" value="Male" id="gender" type="radio" {{ $member->gender == 'Male' ? 'checked' : '' }} /> Male
            </label>
            <label>
                <input name="gender" value="Feale" id="gender" type="radio" {{ $member->gender == 'Female' ? 'checked' : '' }} /> Female
            </label>
            <label>
                <input name="gender" value="3rd Gender" id="gender" type="radio" {{ $member->gender == '3rd Gender' ? 'checked' : '' }}> 3rd Gender
            </label>
        </div>

         @if ($errors->has('gender'))
            <span class="help-block">
                <strong>{{ $errors->first('gender') }}</strong>
            </span>
        @endif
    </div>
</div>

{{-- Permanent Address Section --}}
<div class="form-group">
    {!! Form::label('permanent_address','Permanent Address ',['class' =>'col-md-2 control-label']) !!}
</div>

<!-- Permanent District Form Text Input -->
<div class="form-group{{ $errors->has('perm_address') ? ' has-error' : '' }}">
    <tr>
        <td>
            <!-- District Form Text Input -->
                {!! Form::label('perm_district','District ',['class' =>'col-md-2 control-label']) !!}
            
                <div class="col-md-2">
                    <select class="form-control" name="perm_district">
                        @foreach($districts as $value)
                            <option value="{{ $value }}">{{ $value }}</option>
                        @endforeach
                    </select>
            
                    @if ($errors->has('perm_district'))
                        <span class="help-block">
                            <strong>{{ $errors->first('perm_district') }}</strong>
                        </span>
                    @endif
                </div>
        </td>
        <td>
            <!-- VDC Form Text Input -->
            <!-- VDC Form Text Input -->
                {!! Form::label('perm_vdc','VDC ',['class' =>'col-md-2 control-label']) !!}

                <div class="col-md-2">
                    <select class="form-control" name="perm_vdc">
                        @foreach($vdcs as $value)
                            <option value="{{ $value }}">{{ $value }}</option>
                        @endforeach
                    </select>

                    @if ($errors->has('perm_vdc'))
                        <span class="help-block">
                            <strong>{{ $errors->first('perm_vdc') }}</strong>
                        </span>
                    @endif
                </div>
        </td>
        <td>
            <!-- Ward Form Text Input -->
                {!! Form::label('perm_ward','Ward ',['class' =>'col-md-2 control-label']) !!}
            
                <div class="col-md-1">
                    {!! Form::selectRange('perm_ward', 1, 35, null, ['class'=>'form-control']) !!}
            
                    @if ($errors->has('perm_ward'))
                        <span class="help-block">
                            <strong>{{ $errors->first('perm_ward') }}</strong>
                        </span>
                    @endif
                </div>
        </td>
</div>

{{-- Current Address Section --}}
<div class="form-group">
    {!! Form::label('current_address','Current Address ',['class' =>'col-md-2 control-label']) !!}
</div>

<!-- Country Form Text Input -->
<div class="form-group{{ $errors->has('curr_country') ? ' has-error' : '' }}">
    {!! Form::label('curr_country','Country ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-2">
        <select class="form-control" name="curr_country">
            @foreach($districts as $value)
                <option value="{{ $value }}">{{ $value }}</option>
            @endforeach
        </select>

        @if ($errors->has('country'))
            <span class="help-block">
                <strong>{{ $errors->first('country') }}</strong>
            </span>
        @endif
    </div>
</div>


<!-- Permanent District Form Text Input -->
<div class="form-group{{ $errors->has('curr_address') ? ' has-error' : '' }}">
    <tr>
        <td>
            <!-- District Form Text Input -->
                {!! Form::label('curr_district','District ',['class' =>'col-md-2 control-label']) !!}

                <div class="col-md-2">
                    <select class="form-control" name="curr_district">
                        @foreach($districts as $value)
                            <option value="{{ $value }}">{{ $value }}</option>
                        @endforeach
                    </select>

                    @if ($errors->has('curr_district'))
                        <span class="help-block">
                            <strong>{{ $errors->first('curr_district') }}</strong>
                        </span>
                    @endif
                </div>
        </td>
        <td>
            <!-- VDC Form Text Input -->
                {!! Form::label('curr_vdc','VDC ',['class' =>'col-md-2 control-label']) !!}

                <div class="col-md-2">
                    <select class="form-control" name="curr_vdc">
                        @foreach($vdcs as $value)
                            <option value="{{ $value }}">{{ $value }}</option>
                        @endforeach
                    </select>

                    @if ($errors->has('curr_vdc'))
                        <span class="help-block">
                            <strong>{{ $errors->first('curr_vdc') }}</strong>
                        </span>
                    @endif
                </div>
        </td>
        <td>
            <!-- Ward Form Text Input -->
                {!! Form::label('curr_ward','Ward ',['class' =>'col-md-2 control-label']) !!}

                <div class="col-md-1">
                    {!! Form::selectRange('curr_ward', 1, 35, null, ['class'=>'form-control']) !!}

                    @if ($errors->has('curr_ward'))
                        <span class="help-block">
                            <strong>{{ $errors->first('curr_ward') }}</strong>
                        </span>
                    @endif
                </div>
        </td>
    </tr>
</div>

<!-- Phone No Form Text Input -->
<div class="form-group{{ $errors->has('contact_no') ? ' has-error' : '' }}">
    {!! Form::label('contact_no','Phone No ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-2">
        {!! Form::input('phone','contact_no',null,['class'=>'form-control']) !!}

        @if ($errors->has('contact_no'))
            <span class="help-block">
                <strong>{{ $errors->first('contact_no') }}</strong>
            </span>
        @endif
    </div>
</div>

<!-- Email Form Text Input -->
<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    {!! Form::label('email','Email ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-3">
        {!! Form::input('email','email',null,['class'=>'form-control']) !!}

        @if ($errors->has('email'))
            <span class="help-block">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif
    </div>
</div>

<!-- Skype Form Text Input -->
<div class="form-group{{ $errors->has('skype') ? ' has-error' : '' }}">
    {!! Form::label('skype','Skype ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-3">
        {!! Form::text('skype',null,['class'=>'form-control']) !!}

        @if ($errors->has('skype'))
            <span class="help-block">
                <strong>{{ $errors->first('skype') }}</strong>
            </span>
        @endif
    </div>
</div>

<!-- Qualification Form Text Input -->
<div class="form-group{{ $errors->has('qualification') ? ' has-error' : '' }}">
    <tr>
        <td>
            <!-- Qualification Form Text Input -->
                {!! Form::label('qualification','Qualification ',['class' =>'col-md-2 control-label']) !!}

                <div class="col-md-3">
                    {!! Form::select('qualification' ,[
                        '' =>'',
                        'Under SLC' => 'Under SLC',
                        'SLC'   => 'SLC',
                        'Ten +2' => 'Ten +2',
                        'Bachelor' => 'Bachelor',
                        'Master' => 'Master',
                        'Doctorate' => 'Doctorate',
                        'No Formal Education' => 'No Formal Education'
                    ], null, ['class'=>'form-control']) !!}

                    @if ($errors->has('qualification'))
                        <span class="help-block">
                            <strong>{{ $errors->first('qualification') }}</strong>
                        </span>
                    @endif
                </div>
        </td>
        <td>
            <!-- Specialization Form Text Input -->
            <!-- Specialization Form Text Input -->
                {!! Form::label('specialization','Specialization ',['class' =>'col-md-2 control-label']) !!}

                <div class="col-md-3">
                    {!! Form::text('specialization',null,['class'=>'form-control']) !!}

                    @if ($errors->has('specialization'))
                        <span class="help-block">
                                <strong>{{ $errors->first('specialization') }}</strong>
                            </span>
                    @endif
                </div>
        </td>
    </tr>
</div>

<div class="form-group{{ $errors->has('kind_of_help') ? ' has-error' : '' }}">
    {!! Form::label('kind_of_help','Support By ',['class' =>'col-md-2 control-label']) !!}

    <div class="col-md-4">
        <div class="checkbox">
            <label>
                <input name="kind_of_help" value="Time" type="checkbox" {{ ($member->kind_of_help == 'Time')?'checked="checked':'' }} /> Time
            </label>
            <label>
                <input name="kind_of_help" value="Network" type="checkbox" {{ ($member->kind_of_help == 'Network')?'checked=checked':'' }}> Network
            </label>
            <label>
                <input name="kind_of_help" value="Fund/Resource" type="checkbox" {{ ($member->kind_of_help == 'Fund/Resource')?'checked=checked':'' }}> Fund/Resource
            </label>
        </div>

         @if ($errors->has('kind_of_help'))
            <span class="help-block">
                <strong>{{ $errors->first('kind_of_help') }}</strong>
            </span>
        @endif
    </div>
</div>
<hr/>

<div class="form-group">
    <div class="col-md-offset-5">
        <button type="reset" class="btn btn-primary">
            <i class="fa fa-btn fa-sign-in"></i> Reset
        </button>
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-btn fa-sign-in"></i> {{ $submitText }}
        </button>
    </div>
</div>

resources/views/pages/members/_member_details.blade.php
<table class="table">
    <tbody>
        <tr>
            <td><label>Citizenship No: </label></td>
            <td>{{ $member->citizenship_no }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><label>Date of Birth: </label></td>
            <td>{{ $member->dob }}</td>
            <td><label>Age: </label></td>
            <td></td>
        </tr>
        <tr>
            <td><label>Gender: </label></td>
            <td>{{ $member->gender }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><label>Permanent Address: </label></td>
            <td>{{ $member->perm_vdc.' '.$member->perm_ward.' ,'.$member->perm_district }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><label>Current Address: </label></td>
            <td>{{ $member->curr_vdc.' '.$member->curr_ward.' ,'.$member->curr_district }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><label>Phone no: </label></td>
            <td>{{ $member->contact_no }}</td>
            <td><label>Skype ID: </label></td>
            <td>{{ $member->skype }}</td>
        </tr>
        <tr>
            <td><label>Email ID: </label></td>
            <td>{{ $member->email }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><label>Qualification: </label></td>
            <td>{{ $member->qualification}} {{$member->specialization?'('. $member->specialization .')':' ' }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><label>Help Bibeksheel by: </label></td>
            <td>{{ $member->kind_of_help }}</td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

resources/views/pages/members/create.blade.php
@extends('layouts.template')

@section('content')
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="left pannel-heading">
                    <div class="page-title">
                        <h4>
                            <img class="icon-bar" src="/assets/img/add_user.png" height="25" width="25"></image>
                            Add Member
                        </h4>
                    </div>
                </div>
            </div>

            <div class="panel-body">
                {!! Form::open(['url' => 'members', 'class' => 'form-horizontal']) !!}
                    @include('pages.members._createform')
                {!! Form::close() !!}
            </div>
        </div>
        @include('errors.validError')
    </div>
@endsection

resources/views/pages/members/edit.blade.php
@extends('layouts.template')

@section('content')
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="left pannel-heading">
                    <div class="page-title">
                        <h4>
                            <img class="icon-bar" src="/assets/img/add_user.png" height="25" width="25"></image>
                            Edit Member
                        </h4>
                    </div>
                </div>
            </div>

            <div class="panel-body">
                {{--{{ dd($member) }}--}}
                {!! Form::model($member, ['method' => 'PUT', 'action' => ['MembersController@update',$member->id], 'class' => 'form-horizontal']) !!}
                    @include('pages.members._createform')
                {!! Form::close() !!}
            </div>
        </div>


    </div>


@endsection

resources/views/pages/members/index.blade.php
@extends('layouts.template')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading" style="height: 70px">
            <div class="left pannel-heading" style="float: left;">
                <div class="page-title">
                    <h4>Members</h4>
                </div>
            </div>
            <div class="right_pannel-heading" style="float: right">
                {!! Form::open(['method' => 'GET', 'action' => ['MembersController@index'], 'class'=> "navbar-form navbar-left"]) !!}
                    <div class="form-group">
                        <span class="icon"><i class="fa fa-search"></i></span>
                        {!! Form::input('search','search',null,['id'=> 'searchBox', 'class'=>'form-control', 'placeholder'=>'Search...']) !!}
                    </div>
                   <input type="submit" hidden/>
                {!! Form::close() !!}
                <a href="/members/create"><img src="/assets/img/add_user.png" height="35" width="35"/></a>
                <a href="/members/destroy/"><img src="/assets/img/delete_user.png" height="35" width="35"/></a>
            </div>
        </div>

        <div class="panel-body">
            <div class="membes-pannel">
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Full Name</th>
                                <th>Current Address</th>
                                <th>Permanent Address</th>
                                <th>Contact No</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($members as $member)
                                    <tr>
                                        <td><input type="checkbox" /></td>
                                        <td><a href="{{ url('members',$member->id) }}"> {{ $member->full_name }}</a></td>
                                        <td>{{ $member->curr_vdc.' '.$member->curr_ward.' ,'.$member->curr_district }}</td>
                                        <td>{{ $member->perm_vdc.' '.$member->perm_ward.' ,'.$member->perm_district }}</td>
                                        <td>{{ $member->contact_no }}</td>
                                        <td>Active</td>
                                        <td>
                                            <a href="/members/{!! $member->id !!}/edit"><img src="/assets/img/edit_user.png" height="25" width="25" /></a>
                                            {{--<a href="{!! URL::route('members.destroy',$member->id) !!}"></a>--}}
                                            <script src="https://gist.githubusercontent.com/soufianeEL/3f8483f0f3dc9e3ec5d9/raw/625737f6960776d344a8780265047f608f5153cf/laravel.js" ></script>
                                            <a href="{!! URL::route('members.destroy',$member->id) !!}" data-method="delete" data-token="{{ csrf_token() }}" data-confirm="Are you sure?">
                                                <img src="/assets/img/delete_user.png" height="25" width="25" />
                                            </a>
                                            {{--{!! Form::open(['method' => 'DELETE' ,'action' => ['MembersController@destroy',$member->id], 'class' => 'form-horizontal']) !!}--}}
                                                {{--<button class="btn" type="submit">--}}
                                                    {{--<img src="/assets/img/delete_user.png" height="35" width="25">--}}
                                                {{--</button>--}}
                                            {{--{!! Form::close() !!}--}}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/members/show.blade.php
@extends('layouts.template')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="left pannel-heading"><h4>Member Details: {{ $member->full_name }}</h4></div>
                    </div>

                    <div class="panel-body">
                        <div class="members-pannel col-md-10">
                            @include('pages.members._member_details')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection